batch_size:
  desc: ''
  sort: 0
  value: 16
learning_rate:
  desc: ''
  sort: 1
  value: 0.0001
num_epochs:
  desc: ''
  sort: 2
  value: 20
resize:
  desc: ''
  sort: 3
  value: 224
